### PR TITLE
Guarantee gps fix

### LINKED ISSUE #47: Gaurantee GPS transmission
Must guarantee that the latest GPS coordinates are sent in each packet transmitted over radio.

### PR DESCRIPTION
**Pull request by EliasJRH**
Closes #47 

This PR modifies packet building logic such that each packet obtains the most recently obtained latitude and longitude coordinates if we have a GPS fix.

### CODE REVIEW

File: telemetry/src/collection/collection.c [hunk 1]
```diff
@@ -644,6 +659,8 @@ static void gyro_handler(void *ctx, void *data) {
  * @param gnss_data The gnss data to add
  */
 static void add_gnss_block(collection_info_t *collection, struct sensor_gnss *gnss_data) {
+    collection->last_lat = gnss_data->latitude;
+    collection->last_long = gnss_data->longitude;
```
Comment (AngusJull) [inline telemetry/src/collection/collection.c:663]: Do this in the gnss handler instead, if you can. We don't need to perform this for each block we add (we add a block to the transmit packet we're assembling and to the logging packet we're assembling)

File: telemetry/src/collection/collection.c [hunk 2]
```diff
@@ -492,7 +496,18 @@ static uint8_t *add_or_new(collection_info_t *collection, enum block_type_e type
...
         next_block = pkt_create_blk(collection->current->packet, collection->current->end, type, mission_time);
+        coord_blk_init((struct coord_blk_t *)block_body(next_block), point_one_microdegrees(collection->last_lat),
+                       point_one_microdegrees(collection->last_long));
+        
+                       next_block = pkt_create_blk(collection->current->packet, collection->current->end, type, mission_time);
+        
+        if (collection->last_lat == NAN && collection->last_long == NAN) {
+            inerr("No GPS fix in packet\n");
+            return NULL;
+        }
```
Comment (AngusJull) [inline telemetry/src/collection/collection.c:510]: You could probably check this before adding the GNSS block, and then if we don't have any data don't perform the GNSS add but still proceed. I'm wondering if this will break everything until we have a fix. This also would mean we could run without GNSS data (which happens in development ofc)

File: telemetry/src/collection/collection.c (hunk 1 above)
Comment (EliasJRH) [reply telemetry/src/collection/collection.c:663]: So we'd save the last latitude and longitude readings for each processing context?

File: telemetry/src/collection/collection.c [hunk 3]
```diff
@@ -51,7 +51,7 @@
 #define HAS_MAG
 #endif
 
-#if defined(CONFIG_INSPACE_FAKE_GNSS) || defined(CONFIG_SENSORS_L86XXX)
+#if defined(CONFIG_INSPACE_FAKE_GNSS) || defined(CONFIG_SENSORS_L86_XXX)
```
Comment (linguini1) [inline telemetry/src/collection/collection.c:54]: Lol mb for missing this.

File: telemetry/src/collection/collection.c [hunk 4]
```diff
@@ -492,7 +496,18 @@ static uint8_t *add_or_new(collection_info_t *collection, enum block_type_e type
...
+    
+        /* Always make first block of packet a coords block with most recent coordinates */
         next_block = pkt_create_blk(collection->current->packet, collection->current->end, type, mission_time);
+        coord_blk_init((struct coord_blk_t *)block_body(next_block), point_one_microdegrees(collection->last_lat),
+                       point_one_microdegrees(collection->last_long));
+        
+                       next_block = pkt_create_blk(collection->current->packet, collection->current->end, type, mission_time);
+        
+        if (collection->last_lat == NAN && collection->last_long == NAN) {
+            inerr("No GPS fix in packet\n");
```
Comment (linguini1) [inline telemetry/src/collection/collection.c:508]: This should just be a warning.

File: telemetry/src/collection/collection.c (hunk 2 above)
Comment (linguini1) [reply telemetry/src/collection/collection.c:510]: Sorry yes, we definitely do want to send packets when we don't have a GPS fix. Just not GPS blocks.

The idea is that once we have a GPS fix, no packet should ever be transmitted without at least one coordinate block. That way if we lose packets in flight, we can still recover the rocket.

**Review by linguini1 — CHANGES_REQUESTED** [review]
I agree with Angus's comments, sorry that the wording maybe in #47 wasn't too clear. The idea was that once we have a GPS fix with valid coordinates, every single radio packet must transmit at least one block with our latest coordinates so that if we lose packets, we have a good chance of still recovering the rocket. If we don't have a fix, we should still send packets normally with all other data (except GPS, since we won't have any GPS data without a fix).

File: telemetry/src/collection/collection.c (hunk 1 above)
Comment (AngusJull) [reply telemetry/src/collection/collection.c:663]: Ah mb I understand now why it needs to be done there

**Review by linguini1 — APPROVED** [review]

**Review by linguini1 — APPROVED** [review]
